### ISSUE TITLE
Add Dockerfile 

### ISSUE THREAD

**Issue by OR13** [pq-crystals/kyber#12]
Mac users may prefer to use docker, this works for me:

```
# Pull base image.
FROM ubuntu:latest

# Install.
RUN \
    sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y build-essential && \
    apt-get install -y software-properties-common && \
    apt-get install -y byobu curl git htop man unzip vim wget && \
    apt-get install libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

RUN git clone https://github.com/pq-crystals/kyber.git && \
    cd kyber/ref && make &&\
    cd ../avx2 && make

# Define default command.
CMD ["bash"]
```

I hearby grant permission to the maintainers of this repo to add this code or any modification of it without attribution.

**Comment by cryptojedi** [comment]
Thank you very much for sending this along. I cannot test this and, more importantly, wouldn't want to commit to maintaining it. 
I'll close the issue, but we may want to re-visit this for code in PQCP (https://github.com/pq-code-package).

**Comment by baentsch** [comment]
@OR13 @cryptojedi fyi&fwiw, we have these at varying levels of complexity/integration at https://github.com/open-quantum-safe/oqs-demos (obviously also including kyber and mlkem).
