### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by fizanaaz1995** [pq-crystals/kyber#38]
Kindly confirm which one among the below two licenses are applicable.

    Public Domain (License text - Public domain code is not subject to any license. )
    Creative Commons Zero v1.0 Universal (https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by cryptojedi** [comment]
fizanaaz1995 ***@***.***> wrote:
> Kindly confirm which one among the below two licenses are applicable.
> 
>     Public Domain (License text - Public domain code is not subject to any license. )
>     Creative Commons Zero v1.0 Universal (https://creativecommons.org/publicdomain/zero/1.0/)

Neither "public domain" nor CC0 are licenses. We use the CC0 waiver to
waive our author rights to the maximum extent possible, and thus place
the work into the public domain as far as this is possible. For example,
by European law it is not possible to waive all author rights -- the
only way for any work to truly enter the public domain is for the
author(s) to die and then a certain period of time to pass.
