### ISSUE TITLE
Ask for the link of the security estimation of kyber

### ISSUE THREAD

**Issue by Summwer** [pq-crystals/kyber#46]
Hello, developers of kyber,
    I am an phd candidate work on security estimate, and want to refer to your source code about security estimate of core-SVP at the website:  https://github.com/pq-crystals/kyber/ tree/master/scripts/.  , but found out that the link is deactivated. And wonder ask whether there's any other link about the security estimate of Kyber plz.
    Thanks for reading my request! Best wishes for you!

Wenwen,

2022.1.6

**Comment by cryptojedi** [comment]
The scripts for security estimation for Kyber and Dilithium have moved to a separate repository: https://github.com/pq-crystals/security-estimates
