### ISSUE TITLE
Debugging error PQCgenKAT_kem.c

### ISSUE THREAD

**Issue by KursatCAKAL** [pq-crystals/kyber#57]
How do you debug your code PQCgenKAT_kem.c I am getting below error.

cc -o PQCgenKAT_kem -g2 /Users/kursatc/kyber/ref/PQCgenKAT_kem.c
Undefined symbols for architecture arm64:
  "_pqcrystals_kyber768_ref_dec", referenced from:
      _main in PQCgenKAT_kem-4da757.o
  "_pqcrystals_kyber768_ref_enc", referenced from:
      _main in PQCgenKAT_kem-4da757.o
  "_pqcrystals_kyber768_ref_keypair", referenced from:
      _main in PQCgenKAT_kem-4da757.o
  "_randombytes", referenced from:
      _main in PQCgenKAT_kem-4da757.o
  "_randombytes_init", referenced from:
      _main in PQCgenKAT_kem-4da757.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cryptojedi** [comment]
Kürşat ÇAKAL ***@***.***> wrote:

> How do you debug your code PQCgenKAT_kem.c I am getting below error.
> 
> cc -o PQCgenKAT_kem -g2 /Users/kursatc/kyber/ref/PQCgenKAT_kem.c
> Undefined symbols for architecture arm64:
>   "_pqcrystals_kyber768_ref_dec", referenced from:
>       _main in PQCgenKAT_kem-4da757.o
>   "_pqcrystals_kyber768_ref_enc", referenced from:
>       _main in PQCgenKAT_kem-4da757.o
>   "_pqcrystals_kyber768_ref_keypair", referenced from:
>       _main in PQCgenKAT_kem-4da757.o
>   "_randombytes", referenced from:
>       _main in PQCgenKAT_kem-4da757.o
>   "_randombytes_init", referenced from:
>       _main in PQCgenKAT_kem-4da757.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

What exactly are you doing to get to this error? When I run `make
PQCgenKAT_kem512` in the `main` branch, it compiles just fine.

**Comment by KursatCAKAL** [comment]
I am trying to debug code step by step in CLion. Did you try it ?

**Comment by KursatCAKAL** [comment]
Sorry for missing some details.

If you want to debug your project. You need below steps:

1-) Create CMakelist.txt 
2-) Include it into your project folder.
3-) Open your project folder with CLion.
4-) Select CMake project in "Open or Import Project" window
5-) Make sure related configurations are generated in "Open Project Wizard" window.
Related configurations means that Build Type, Toolchain, Generator, CMake Options etc.
6-) CLion will generate debug options.


My CMake

**Comment by cryptojedi** [comment]
I'm using a combination of printf-debugging and gdb. I have never used CLion and I'm afraid I cannot offer help here.

**Comment by KursatCAKAL** [comment]
Thank you.
