### ISSUE TITLE
About the plaintext length of CPAPKE

### ISSUE THREAD

**Issue by qinleiyong** [pq-crystals/kyber#70]
May I ask why CPAPKE can only encrypt data with a fixed length of 32 bytes? I don't seem to have found any explanation about this in the document. Does this mean that I cannot consider CPAPKE as a public key encryption scheme that can replace RSA?

**Comment by cryptojedi** [comment]
You should not use the PKE as a standalone primitive at all. Kyber is a KEM and then entry points are the crypto_kem_* functions. You can use the KEM to build a PKE using the KEM/DEM construction.
