### ISSUE TITLE
randombytes_custom_algorithm supporrt

### ISSUE THREAD

**Issue by vkosuri** [pq-crystals/kyber#72]
do we have a similar API like liboqs https://github.com/open-quantum-safe/liboqs/blob/bdce95401037aef04fd78f7674aef76bdb435ff2/src/common/rand/rand.h#L46

Are there any plans to support this feature?

**Comment by cryptojedi** [comment]
We do not have such an interface to obtain randomness and there is also no
concrete plans to add it.  However, in the ```standard``` branch, there are
derandomized versions of the API, so you can call whatever function you want
to obtain randomness and then feed this as an argument into these derandomized
API functions.

**Comment by vkosuri** [comment]
Thanks @cryptojedi
