### ISSUE TITLE
Resize the buffer size in `gen_matrix`

### ISSUE THREAD

**Issue by cothan** [pq-crystals/kyber#79]
The `buf` size is larger than its usage by 2 bytes. 
As in https://github.com/pq-crystals/kyber/blob/d1321ce5ac0b53f583eb47a040dc3625ee8e7e37/ref/indcpa.c#L165

The actual needed size for `buf` is indicated at:
 https://github.com/pq-crystals/kyber/blob/d1321ce5ac0b53f583eb47a040dc3625ee8e7e37/ref/indcpa.c#L176

I think the `+2` is redundant. 

I suggest resizing `buf` to its actual need size 504 bytes `(504 % 8 == 0)`. The current size is 506 bytes = `GEN_MATRIX_NBLOCKS * XOF_BLOCKBYTES + 2`, creates load/store operation to the buffer unaligned.

**Comment by cryptojedi** [comment]
Fixed in the "standard" branch (together with issue 74)
