### ISSUE TITLE
Is latest code of kyber in this github is FIPS 203?

### ISSUE THREAD

**Issue by ranjankumar23** [pq-crystals/kyber#87]
Is latest code of kyber in this github is FIPS 203?

Because in code i see file fips202. 

Since i am not expert, i need your help for confirmation.

**Comment by cryptojedi** [comment]
Aside from input validation, the code as it is now should implement FIPS 203. The reason to have a file called fips202.c (and .h) is that ML-KEM uses functions from FIPS 202 for symmetric crypto.
