### ISSUE TITLE
OpenSSL v3?

### ISSUE THREAD

**Issue by hackerfactor** [pq-crystals/kyber#89]
OpenSSL v1.x is obsolete (as of earlier this year).
Are there any plans to make this support OpenSSL v3.x?

**Comment by cryptojedi** [comment]
We use OpenSSL only as a dependency for the NIST-provided files that generate test vectors in NIST format.
If NIST provides updated files that link against OpenSSL 3.x, I'm happy to integrate those; if you are
aware of such updates to the NIST-provided code, please re-open the issue. For now, I'll close it.
